config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div>
  <p>
    <strong><%= flat.name %></strong>
  </p>

  <p>
    <strong><%= flat.address %></strong>
  </p>

  <p>
    <strong><%= flat.price_per_night %> € </strong>
  </p>

  <p>
    <strong><%= flat.number_of_guests %> guests </strong>
  </p>

  <p>
    <strong><%= flat.description %> </strong>
  </p>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for [@flat] do |f|%>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/_list.html.erb
<div id="flats">
  <% flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "More info", flat %>
      <%= link_to "Edit", edit_flat_path(flat.id) %>
      <%= link_to "Remove", flat_path(flat.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </p>
  <% end %>
</div>

app/views/flats/edit.html.erb
<h1>Edit <%= @flat.name %></h1>
<div>
 <%= render "form" %>
</div>

app/views/flats/index.html.erb
<h1 class="text-center">All the flats</h1>
<h4 class="text-center">There are <%= Flat.count %> flats available</h4>

<div class="container">
  <div class="flats-cards-container">
    <% @flats.each do |flat| %>
      <div class="flat-card">
        <div>
          <h3><%= flat.name %></h3>
          <h5><%= flat.address %></h5>
          <h5><%= flat.price_per_night %> €/night</h5>
          <h5><%= flat.number_of_guests %> guests</h5>
        </div>
        <div class="flat-card-links">
          <%= link_to "More info", flat%>
          <%= link_to "Edit", edit_flat_path(flat.id), class: "text-warning" %>
          <%= link_to "Remove", flat_path(flat.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-danger" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add a flat</h1>

<div>
 <%= render "flats/form" %>
</div>

app/views/flats/show.html.erb
<%= render @flat %>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Simple Airbnb</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto flex">
        <%# <form class="flex my-2 my-lg-0">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> %>
        <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
      </div>
    </div>
  </div>
</nav>